apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: redcap-yourdomain-org-tls
  namespace: redcap
spec:
  secretName: tredcap-yourdomain-org-tls
  issuerRef:
    name: letsencrypt
  commonName: redcap.yourdomain.org
  dnsNames:
  - redcap.yourdomain.org
  acme:
    config:
    - http01:
        ingress: redcapweb
      domains:
      - redcap.yourdomain.org