apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: redcap-nfs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
